@startuml

skinparam monochrome true

package "Domain Model" as model {
    class Feed {
        name
        language
        {static} baseUrl
        addItem()
        removeItem()
    }

    class Site {
        siteUrl
        logoUrl
        rightsStatement
        contactEmail
    }

    class FeedItem {
        date
        title
        url
        description
    }

    class FulltextFeedItem {
        bodyText
    }

    class Image {
        url
        width
        height
        altText
        copyrightHolder
    }
}

package "Application Services" as services {
    class FeedBroker {
        processRequest()
        logonUser()
    }

    class Logger {
        logAccess()
    }

    class Authorisation
}

services ..> model: <<access>>

Feed "0..*" - "1" Site : has <
Feed "1" -- "1..*" FeedItem : contains >
FeedItem "1" -> "1" Image

FulltextFeedItem -|> FeedItem

FeedBroker -- Logger
FeedBroker -- Authorisation

hide circle
hide empty methods
hide empty attributes

@enduml
