@startuml

actor ":Subscriber" as subscriber
participant ":FeedBroker" as broker
participant "mundoFeed:Feed" as mundoFeed

subscriber -> broker: getFeed("mundo")
activate broker

note left
    The Subscriber requests
    a specific feed
end note

broker -> broker: isValid = validateFeed("mundo")
activate broker
broker --> broker
deactivate broker

alt isValid

    broker --> subscriber: error

note left
    If the feed is invalid
    an error is returned
end note

else else

    broker -> broker: generateFeed("mundo")
    activate broker

    create mundoFeed
    broker -> mundoFeed: <<create>>

    note left
        Otherwise the system generates
        a new feed
    end note

    broker --> broker
    deactivate broker

    broker --> subscriber: mundoFeed
    deactivate broker

end

hide footbox

@enduml
