@startuml
left to right direction

actor Subscriber
actor FulltextSubscriber
actor Journalist
actor AudiencesAnalyst

rectangle FeedManager {
  Subscriber -> (ListFeeds)
  Subscriber -> (GetFeed)
  FulltextSubscriber -> (GetFulltextFeed)
  (CreateContent) <- Journalist
  (UpdateContent) <- Journalist
  (CreateUsageReport) <- AudiencesAnalyst
}

@enduml

